spring:
  application:
   name: TravelAPI
  datasource:
   url: ${DATASOURCE_URL}
   username: ${DATASOURCE_USERNAME}
   password: ${DATASOURCE_PASSWORD}
   driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
